// <auto-generated />
namespace WikY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CREATING_ARTICLES_AND_COMMENTS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CREATING_ARTICLES_AND_COMMENTS));
        
        string IMigrationMetadata.Id
        {
            get { return "202005220908468_CREATING_ARTICLES_AND_COMMENTS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
