// <auto-generated />
namespace WikY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MODIFY_NAME_OF_CREATIONDATE_PROPERTY_IN_ARTICLES : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MODIFY_NAME_OF_CREATIONDATE_PROPERTY_IN_ARTICLES));
        
        string IMigrationMetadata.Id
        {
            get { return "202005220941011_MODIFY_NAME_OF_CREATIONDATE_PROPERTY_IN_ARTICLES"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
